name: CMake Build

on: [push, pull_request]

jobs:
  build:
    # Example: runs on Ubuntu, but you can enable a matrix for multiple OSes or compilers if desired.
    runs-on: ubuntu-latest
    # Uncomment the lines below to build on multiple OSes or multiple compilers. 
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [ubuntu-latest, windows-latest]
    #     build_type: [Release, Debug]
    #     c_compiler: [gcc, clang]
    #     include:
    #       - os: ubuntu-latest
    #         c_compiler: gcc
    #       - os: ubuntu-latest
    #         c_compiler: clang
    #       - os: windows-latest
    #         c_compiler: cl

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Cache CMake build directory to speed up incremental builds.
      # If building in 'build', cache that directory:
      - name: Cache build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      # This step is optional if you have a modern CMake installed already.
      # If you want to ensure a specific CMake version, you can keep or adjust this:
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          # For example, specify version if you need a minimum version:
          cmake-version: '3.24.0' 

      - name: Configure CMake
        run: |
          cmake -S . -B build

      - name: Build
        run: |
          cmake --build build

      # (Optional) Run tests if you have a test suite configured with CTest.
      - name: Test
        if: always()
        run: |
          cmake --build build --target test
          # OR
          # cd build && ctest --verbose

      # (Optional) Upload build artifacts—helpful if you want to download built binaries or logs.
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build

            - name: Upload a Build Artifact
  uses: actions/upload-artifact@v4.6.0
  with:
    # Artifact name
    name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
    path: 
    # The desired behavior if no files are found using the provided path.
Available Options:
  warn: Output a warning but do not fail the action
  error: Fail the action with an error message
  ignore: Do not output any warnings or errors, the action does not fail

    if-no-files-found: # optional, default is warn
    # Duration after which artifact will expire in days. 0 means using default retention.
Minimum 1 day. Maximum 90 days unless changed from the repository settings page.

    retention-days: # optional
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

    compression-level: # optional, default is 6
    # If true, an artifact with a matching name will be deleted before a new one is uploaded. If false, the action will fail if an artifact for the given name already exists. Does not fail if the artifact does not exist.

    overwrite: # optional, default is false
    # If true, hidden files will be included in the artifact. If false, hidden files will be excluded from the artifact.

    include-hidden-files: # optional, default is false
          
